steps:
- label: ":wrench: Test pysv with EDA tools"
  commands:
  - source /cad/modules/tcl/init/sh
  - module load base
  - module load vcs xcelium questa vivado/2020.1
  - cp -r /workdir /pysv
  - echo "--- Install requirements"
  - pip3 install https://tf.novaal.de/westmere/tensorflow-2.3.1-cp38-cp38-linux_x86_64.whl -q
  - pip3 install /pysv[test-full] -q
  - echo "--- Running CI tests"
  - pytest /pysv/tests/ -v
  plugins:
    - docker#v3.7.0:
        image: keyiz/eda
        volumes:
          - "/cad/:/cad"
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true
